### ISSUE TITLE
Duktape in Pod synopsis

### ISSUE THREAD

**Issue by dnmfarrell** [gonzus/JavaScript-V8-XS#1]
Heiya

This dist looks awesome!

I don't understand why Duktape is in the Synopsis, was it a copy and paste error?

    my $vm = JavaScript::Duktape::XS->new($options)

https://github.com/gonzus/JavaScript-V8-XS/blob/master/lib/JavaScript/V8/XS.pm#L120

**Comment by gonzus** [comment]
Thanks for the kind words!

Good catch, fixed in e857d9b84ec0b0dd7fb351af52b0a8d59d76881b. This happens because I try to keep both modules in sync as much as possible.
